### PR TITLE
Converted from print to yield to make functions friendlier to import.…

### PR DESCRIPTION
**Pull request by clawsoon**
…  Switched from sys.argv to argparse for friendlier help messages.

### CODE REVIEW

**Comment by jakubcerveny** [comment]
Great, thanks! 

One question: are the new `--width` and `--height` parameters mandatory, or can they also be used as positional parameters (so the old command-line still works)?

**Comment by clawsoon** [comment]
Width and height arguments should work exactly the same as the old ones did, i.e.:

    ./gilbert2d 4 6

I did consider adding arguments for starting x and y, and for forcing the major axis (and I'm using it that way in some of the examples I'm making), but I figured that might be more changes than you'd want to make.  For that you'd use it like this:

    ./gilbert2d 4 6 -x 300 -y 10 -a width

...and the code would look something like this:

    def gilbert2d(width, height, x=0, y=0, axis=None):

        if not axis:
            axis = 'width' if abs(width) >= abs(height) else 'height'

        if axis == 'width':
            yield from _gilbert2d(x, y, width, 0, 0, height)
        elif axis == 'height':
            yield from _gilbert2d(x, y, 0, height, width, 0)
        else:
            raise Exception('Unrecognized axis')

    def parse_arguments():

        import argparse

        parser = argparse.ArgumentParser()

        parser.add_argument('width', type=int)
        parser.add_argument('height', type=int)
        parser.add_argument('-x', '--starting-x', type=int, default=0,
                help='Optional starting x.')
        parser.add_argument('-y', '--starting-y', type=int, default=0,
                help='Optional starting y.')
        parser.add_argument('-a', '--axis', type=str, default=None,
                help='Optional major axis (defaults to larger of width or height).')

        args = parser.parse_args()

        return args


    if __name__ == '__main__':

        args = parse_arguments()

        for x, y in gilbert2d(args.width, args.height, args.starting_x, args.starting_y, args.axis):
            print(x, y)

**Comment by jakubcerveny** [comment]
OK thanks, I think the width/height only version is good. 

I'm gonna merge this and make two more minor changes: I'll probably rename `_gilbert2d` to `generate2d` and I'll move `gilbert2d` to the top of the file (with the docstring), is that OK with you (and is that the right thing to do in Python)?

Thanks again.

**Comment by clawsoon** [comment]
That all sounds good to me.

**Pull request merged**
